name: Node version setup

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get .nvmrc content
        id: get_nvmrc
        run: |
          nvmrc_content=$(curl https://api.github.com/repos/rishiip/test-curl/contents/.nvmrc | jq -r '.content' | base64 --decode)
          echo "::set-output name=nvmrc_content::$nvmrc_content"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.get_nvmrc.outputs.nvmrc_content }}
